# WEEK 1

In [203]:
a=11
b=a*10
print(a,b)

11 110


In [176]:
a=14
b=a*10
print(a,b)

14 140


In [204]:
# simple example
# calculate valume of cylinder
dia =5  ## dia is for dimeter
len =4  ## len for length
vol = 2*3.141*(dia/2)**2*len
print(vol)

157.05


In [178]:
import numpy as np

In [205]:

Physics,Mathematics,Chemistry = 70,80,90

print(Physics,Mathematics,Chemistry)
print(Physics+Mathematics)
print(Chemistry-Mathematics)
print(Chemistry*Physics)

70 80 90
150
10
6300


In [206]:
type(Physics)

int

In [207]:
employee_name,age,height ="Ram",55,150.6
type(employee_name)
type(age)
type(height)
print(employee_name,age,height,type(employee_name),type(age),type(height))

Ram 55 150.6 <class 'str'> <class 'int'> <class 'float'>


In [208]:
type(height) is int  # verifyig data type

False

In [209]:
type(age) is float

False

In [210]:
type(employee_name) is str

True

## Convert the data type of an object to another

In [211]:
type(height)

float

In [212]:
ht = int(height)
print(ht,type(ht))

150 <class 'int'>


In [214]:
height=int(height)
type(height)

int

In [215]:
salary_tier ='1'
type(salary_tier)
print(salary_tier,type(salary_tier))

1 <class 'str'>


In [216]:
salary_tier=int(salary_tier)
type(salary_tier)


int

# OPERATORS

In [190]:
2+3 # here + is operator  2,3 are operands

5

In [217]:
# + ADDITION
# - SUBSTRACTION
# * MULTIPLICATION
# / DIVISION
# % REMINDER
# ** EXPONENT 

In [218]:
a = 7-2*(27/3**2)+4
print(a)

5.0


In [219]:
# ASSIGNMENT OPERATOR
# =  EX- a=10  b=5
# += means a=a+b
# -= means a=a-b
# *= means a=a*b
# /= means a=a/b

In [220]:
a=10 
b=5
a+=b
print(a) #now a = 15

a-=b
print(a)

a*=b
print(a)

a/=b
print(a)


15
10
50
10.0


In [221]:
x=5
y=7

In [222]:
# RELATIONAL OPERATOR

print(x<y)  ## strictly less than
print(x<=y)  ## Less than or equal to
print(x>y)  ## strictly greater than
print(x>=y)  ## Greater than or equal to
print(x==y)  ## Equal to equal to
print(x!=y)   ## Not equal to

True
True
False
False
False
True


In [197]:
## LOGICAL  OPERATOR

# or         Logical OR

print((x>y) or (x<y))

# and        Logical AND
print((x>y) and (x<y))

# not        Logical NOT
print(not(x==y))

True
False
True


In [223]:
# BITWISE OPERATOR
## WE USE ONLY WHEN OPERANDS ARE IN INTEGER

# Bitwise OR(|),AND(&)
print(x|y)
print((x<y)|(x==y))

7
True


# ASSIGNMENT FIRST

In [224]:
k=2+3j
print(k)
L= complex(2,3)
print(L)
# m=2+3I
# print(m)
m=2+3J
print(m)

(2+3j)
(2+3j)
(2+3j)


In [225]:
7//2

3

In [226]:
#question 1
a,b ='4','6'
print(a+b)

46


In [227]:
#question 2
var@check1=10

SyntaxError: cannot assign to operator (2679787646.py, line 2)

In [228]:
#question 3
X=3
Y=6
print(X,Y)

X,Y=Y,X

print(X,Y)

3 6
6 3


In [229]:
#question 4
y=1**2**3**2
print("Varible:",y)

Varible: 1


In [230]:
#question 5
j=5
k=11
print(j|k)

j=7
print(j|k)

15
15


In [231]:
#question 6
log_exp = not not True and False or not False
print(log_exp)

True


In [232]:
#question 7
k=4%7
print(k,type(k))

4 <class 'int'>


In [233]:
#question 8
p=6/3.3
q=6//3.3
print(p,q,type(p),type(q))

1.8181818181818183 1.0 <class 'float'> <class 'float'>


In [234]:
#question 9
answer1 = True
answer2 = False
print(answer1*answer2)

0


In [235]:
#question 10
print("Good",end="")
print("Day")

word1 ="Trial"
print("Word is %s"%word1)

num1 =23
print("Number:%f"%num1)

print("ready\nsteady\ngo")

GoodDay
Word is Trial
Number:23.000000
ready
steady
go


# WEEK 2

### LIST

In [312]:
id = [1,2,3,4]
employee_name = ["Ram","Preeti","Satish","John"]
num_emp =4

employee_list = [id,employee_name,num_emp]
print(employee_list)

[[1, 2, 3, 4], ['Ram', 'Preeti', 'Satish', 'John'], 4]


## INDEX

+ve indexing start with 0  & -ve indexing start with -1

In [313]:
# to extract id fron employee list
print(employee_list[0])  # here zero is index for id   by +ve indexing
print(employee_list[1])  # here zero is index for employee_name

[1, 2, 3, 4]
['Ram', 'Preeti', 'Satish', 'John']


In [314]:
print(employee_list[1][1])

Preeti


In [315]:
print(employee_list[0][1])

2


In [316]:
# how to modify the list
print(employee_list)  ## existing list

[[1, 2, 3, 4], ['Ram', 'Preeti', 'Satish', 'John'], 4]


In [317]:
# we want to change num_emp from 4 to 5
employee_list[2]=5
print(employee_list)

[[1, 2, 3, 4], ['Ram', 'Preeti', 'Satish', 'John'], 5]


In [318]:
# i want to change the value at sub level component
employee_list[1][3]="Karan"
print(employee_list)

[[1, 2, 3, 4], ['Ram', 'Preeti', 'Satish', 'Karan'], 5]


MODIFICATION BY INBUILD FUNCTION



In [319]:
#Adding number '5' to the level id in employee_list
employee_list[0].append(5)
employee_list[1].append('Nirmal')
print(employee_list)

[[1, 2, 3, 4, 5], ['Ram', 'Preeti', 'Satish', 'Karan', 'Nirmal'], 5]


In [320]:
# Adding a list to a list
# adding a new list age to the existing employee_list
age=[23,25,36,43,52]
employee_list.append(age)  ## we can also put [23,25,36,43,52] at place of age
print(employee_list)

[[1, 2, 3, 4, 5], ['Ram', 'Preeti', 'Satish', 'Karan', 'Nirmal'], 5, [23, 25, 36, 43, 52]]


In [321]:
print(employee_list)

[[1, 2, 3, 4, 5], ['Ram', 'Preeti', 'Satish', 'Karan', 'Nirmal'], 5, [23, 25, 36, 43, 52]]


In [322]:
## insert function
# list_name[index].insert(position,object)
print(employee_list)  ## existing list

[[1, 2, 3, 4, 5], ['Ram', 'Preeti', 'Satish', 'Karan', 'Nirmal'], 5, [23, 25, 36, 43, 52]]


In [323]:
# Adding number 6 at the first position to the level id from employee_list
employee_list[0].insert(0,6)
print(employee_list) 

[[6, 1, 2, 3, 4, 5], ['Ram', 'Preeti', 'Satish', 'Karan', 'Nirmal'], 5, [23, 25, 36, 43, 52]]


In [324]:
#  remove element from the list
 
# del-remove the object at the specified index number

# syntax- del list_name[index1][index2]

# index1-index of top level of componentto be dropped

# index2- index of sub level of componentto be dropped

print(employee_list)  ## existing list

[[6, 1, 2, 3, 4, 5], ['Ram', 'Preeti', 'Satish', 'Karan', 'Nirmal'], 5, [23, 25, 36, 43, 52]]


In [325]:
# drop the last level i.e. age from employee _list
del employee_list[3]
print(employee_list) 

[[6, 1, 2, 3, 4, 5], ['Ram', 'Preeti', 'Satish', 'Karan', 'Nirmal'], 5]


In [326]:
# by remove function
    
#syntax- list_name[indec].remove(object)

print(employee_list)  ## existing list

[[6, 1, 2, 3, 4, 5], ['Ram', 'Preeti', 'Satish', 'Karan', 'Nirmal'], 5]


In [327]:
# remove Ram from the level employee_name from employee_list
employee_list[1].remove("Ram")
print(employee_list)

[[6, 1, 2, 3, 4, 5], ['Preeti', 'Satish', 'Karan', 'Nirmal'], 5]


In [328]:
# consiser another list
salary = ["High","Low","Medium","Low"]
print(salary)

['High', 'Low', 'Medium', 'Low']


In [329]:
salary.remove("Low")
print(salary)

['High', 'Medium', 'Low']


In [330]:
# Modifying component using pop()

# syntax- list_name[index1].pop(index2)

print(employee_list)

[[6, 1, 2, 3, 4, 5], ['Preeti', 'Satish', 'Karan', 'Nirmal'], 5]


In [331]:
# removing number 4 from the 5th position of id level from employee_list
employee_list[0].pop(4)

4

In [332]:
print(employee_list)


[[6, 1, 2, 3, 5], ['Preeti', 'Satish', 'Karan', 'Nirmal'], 5]


# TUPLES

In [333]:
# Create tuple with employee id,name,age,salary detail
employee_details = ('P001','John',35,40000)
print(employee_details)

('P001', 'John', 35, 40000)


In [336]:
# Accessing component of tuple
# syntax- tuple_name[index]
employee_details[0]   #  to extract id from employee_detail
print(employee_details[0])

P001


In [337]:
# to extract salary from employee_detail
print(employee_details[3])

40000


In [339]:
print(employee_details[5]) ## here it show error because index ois up to 3

IndexError: tuple index out of range

### Slicing

In [340]:
# to extract name & age  from employee_detail
print(employee_details[1:3])  # here 1 included and 3 excluded

('John', 35)


In [341]:
# to extract id ,name & age  from employee_detail
print(employee_details[:3])

('P001', 'John', 35)


In [344]:
## LENGTH OF THE TUPLE
# Syntax- len(tuple_name)

len(employee_details)

TypeError: 'int' object is not callable

In [345]:
# Finding Minimum & Maximum from the tuple
# min(tuple_name),max(tuple_name)

In [346]:
english = (56,85,96,75,12)

In [348]:
min(english)

12

In [349]:
max(english)

96

In [350]:
# Combining two or more tple
# two tuple can be concatenated as (tuple1)+(tuple2)

In [351]:
employee_details2 = ('M.Com','Accounts')

In [352]:
print(employee_details)  ## tuple1
print(employee_details2)  ## tuple2

('P001', 'John', 35, 40000)
('M.Com', 'Accounts')


In [353]:
print(employee_details+employee_details2) ## combined two tuple

('P001', 'John', 35, 40000, 'M.Com', 'Accounts')


In [354]:
## Modifying component of tuple
## once tuple be created we cannot be modify

# Dictionary

In [1]:
Fuel_type = { "Petrol":1,"Diesel":2,"CNG":3}
print(Fuel_type)

{'Petrol': 1, 'Diesel': 2, 'CNG': 3}


In [2]:
print(Fuel_type['Petrol'])

1


In [3]:
print(Fuel_type['CNG'])

3


In [4]:
##  to acces the keys from dictionary Fuel_type
# syntax - dictionary_name.keys()

Fuel_type.keys()

dict_keys(['Petrol', 'Diesel', 'CNG'])

In [5]:
##  to acces the values from dictionary Fuel_type
# syntax - dictionary_name.values()
Fuel_type.values()

dict_values([1, 2, 3])

In [6]:
##  to acces both keys and values simultaneously from dictionary Fuel_type
# syntax - dictionary_name.items()
Fuel_type.items()

dict_items([('Petrol', 1), ('Diesel', 2), ('CNG', 3)])

In [7]:
# Modifying a dictionary
# Adding new key value pair to the existing dictionary Fuel_type
# syntax - dictionary_name[key]=value
Fuel_type['electric']=4

In [8]:
print(Fuel_type)

{'Petrol': 1, 'Diesel': 2, 'CNG': 3, 'electric': 4}


In [9]:
# USING INBUILT FUNCTION update()
# syntax - dictionary_name.update({key:value})
Fuel_type.update({'solar':5})
print(Fuel_type)

{'Petrol': 1, 'Diesel': 2, 'CNG': 3, 'electric': 4, 'solar': 5}


In [10]:
# modifying the value of an existing key
Fuel_type['CNG']=7
print(Fuel_type)

{'Petrol': 1, 'Diesel': 2, 'CNG': 7, 'electric': 4, 'solar': 5}


In [11]:
# how to remove component of dictionary usinf del()
# syntax- del dictionary_name[key]
# Dropping solar from Fuel_type
del Fuel_type['solar']

In [12]:
print(Fuel_type)

{'Petrol': 1, 'Diesel': 2, 'CNG': 7, 'electric': 4}


In [13]:
## using clear()
# clear()- remove all the key value pairs
# syntax- dictionary_name.clear()
Fuel_type.clear()

In [14]:
print(Fuel_type)   ## it give null dictionary

{}


# Sets

In [15]:
age = {56,52,41,63,41} ## set does not hold duplicate items
print(age)              ## so only single 41 will appear

{56, 41, 52, 63}


In [16]:
employee_name = {'Ram', 'Preeti', 'Satish', 'John', 'Nirmal'}
print(employee_name)  ## order will not be same,it is an unordered set

{'Nirmal', 'Satish', 'John', 'Preeti', 'Ram'}


In [18]:
# Modify set using add()
# Syntax- set_name.add(object)
employee_name.add('Ganesh')
print(employee_name)

{'Nirmal', 'Satish', 'Ganesh', 'John', 'Preeti', 'Ram'}


In [19]:
# remove element from existing sets using discard()
# discard()- remove matching object from existing set
# syntax - set_name.discard(object)
employee_name.discard("John")
print(employee_name)

{'Nirmal', 'Satish', 'Ganesh', 'Preeti', 'Ram'}


In [20]:
# Modify using clear()
# clear()-removes all the elements from the existing set
# syntax - set_names.clear()
employee_name.clear()
print(employee_name)  # it gives null sets

set()


### Set operations

In [21]:
Junior_datascientist = {"R","Python","Tableau"}
Datascientist = {"R","Python","Scala","Java","Tableau"}

In [23]:
print(Junior_datascientist)
print(Datascientist)

{'R', 'Python', 'Tableau'}
{'Tableau', 'R', 'Python', 'Java', 'Scala'}


In [24]:
# SET UNION
# union()-returns all elements belonging to both set A and B
# SYNTAX: set_A.union(set_B)
Junior_datascientist.union(Datascientist )

{'Java', 'Python', 'R', 'Scala', 'Tableau'}

In [25]:
# SET INTERSECTION
# intersection()-returns  elements common to both  A and B
# SYNTAX: set_A.intersection(set_B)
intersection=Junior_datascientist.intersection(Datascientist )
print(intersection)

{'R', 'Python', 'Tableau'}


In [26]:
# SET DIFFERENCE
# difference()-returns elements belongaging to A but not B
# SYNTAX: set_A.difference(set_B)
diff = Junior_datascientist.difference(Datascientist)
print(diff)

set()


In [27]:
# Symmetric difference
# symmetric_difference()- returns elements not common to both sets
# SYNTAX: set_A.symmetric_difference(set_B)
symm_diff = Junior_datascientist.symmetric_difference(Datascientist)
print(symm_diff)

{'Java', 'Scala'}


# NumPy

In [28]:
import numpy as np

In [29]:
x = np.array([2,3,4,5])
print(type(x))

<class 'numpy.ndarray'>


In [30]:
print(x)

[2 3 4 5]


In [32]:
x=np.array([2,3,'n',5])
print(x)
print(type(x))

['2' '3' 'n' '5']
<class 'numpy.ndarray'>


In [33]:
# Generating arrays by linspace()
=the sample number
# Syntax: numpy.linspace(start,stop,num,dtype,retstep)
# start:- start of interval range
# stop:- end of interval range
# num:-  number od sample to generated
# dtype:- type of output array
# retstep:- return the sample,step value

b = np.linspace(start=1, stop=5, num=10, endpoint=True, retstep=False) 
print(b)
# endpoint means we want to include last value or not
# retstep False means it returns only samle and not the increment value # means it is for size interval

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [34]:
c = np.linspace(start=1, stop=5, num=10, endpoint=True, retstep=True) 
print(c)

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]), 0.4444444444444444)


In [36]:
# GENERATING arrays using arange()
# numpy.arange()-returns equally spaced numbers with in the given range based on 
# Syntax: numpy.arange(start,stop,step)
d = np.arange(start =1,stop=10,step=2)
print(d)

[1 3 5 7 9]


In [42]:
# GENERATING arrays using ones()
# numpy.ones()- returns an array of given shape and type filled with ones
# Syntax:- numpy.ones(shape,dtype)
# dtype:- data type(default:float)
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
np.ones((3,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [41]:
# GENERATING arrays using zeros()
# numpy.zeros()- returns an array of given shape and type filled with zeros
# Syntax:- numpy.zeros(shape,dtype)
# dtype:- data type(default:float)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.zeros((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [48]:
# GENERATING arrays using random.rand()
# numpy.random.rand()- returns an array of given shape filled with random values
#Syntax:- numpy.random.rand(shape)
np.random.rand(5)

array([0.71955118, 0.13575601, 0.03528738, 0.6924016 , 0.32942186])

In [49]:
np.random.rand(5,2) # RANDOM VALUE WITH 5 ROWS AND 2 COLOUMN

array([[0.46096721, 0.53376635],
       [0.15761812, 0.74463835],
       [0.16042154, 0.22299968],
       [0.77818218, 0.82752143],
       [0.95991767, 0.86281427]])

In [50]:
# GENERATING arrays using logspace()
# numpy.logspace()- returns equally spaced number based on log scale
# Syntax:- numpy.logspace(start,stop,num,endpoint,base,dtype)
# start:- start value of the sequence
# stop:- end value of the sequence
# num:- number of sample to generate (default:50)
# endpoint:- if True, stop is the last number
# Base:- base on log space(default:10.0)
# dtype:- type of output array
np.logspace(1,10,num=5,endpoint=True,base=10.0)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

### Advantage of numpy

1ST TIMING

In [52]:
# Creating a list
x = range(1000)


In [54]:
timeit sum(x)

43.4 µs ± 383 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [55]:
# Creating numpy array
y=np.array(x)

In [57]:
timeit sum(y)

216 µs ± 16.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


2ND STORAGE

In [58]:
# getsizeof()- returns the size of the object in bytes
# Syntax: sys.getsizeof(object)

# itemsize- returns the size of one element of a numpy array
# Syntax:- numpy.ndarray.itemsize

In [59]:
import sys

In [60]:
sys.getsizeof(1) * len(x)

28000

In [61]:
y.itemsize * y.size

4000

## Reshaping an array

In [65]:
# reshape()- recasts an array to new shape without changing its data
grid = np.arange(start=1,stop=10).reshape(3,3)
print(grid)
grid1 = np.arange(start=1,stop=10).reshape(1,9)
print(grid1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]


In [67]:
# Array Dimension

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
## shape()- returns dimension of an array
## Syntax:- array_name.shape

a.shape

(3, 3)

In [70]:
# Numpy Addition

# numpy.add()- perform element wise addition between two array
# Syndax: numpy.add(array_1,array_2)

In [71]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.arange(start=11,stop=20).reshape(3,3)

In [72]:
print(a,b)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[11 12 13]
 [14 15 16]
 [17 18 19]]


In [73]:
np.add(a,b)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [75]:
# Numpy multipication
# numpy.multiply()- perform element wise multiplication between two array
# Syndax: numpy.multiply(array_1,array_2)
np.multiply(a,b)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [76]:
# Other numpy function

# numpy.subtract()
# numpy.divide()
# numpy.remainder()

In [77]:
# Accessing component of an array
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [78]:
# we want to extract element of array frow 1st row and 2nd coloum  #(0,1)
a[0,1]

2

In [80]:
a[2,2]

9

In [81]:
# extract element from 2nd and 3rd row of array a
a[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [82]:
#extract element from first column of aaray a
a[:,0]

array([1, 4, 7])

In [83]:
a[:,2]

array([3, 6, 9])

In [84]:
# extract element from first row of arraw a
a[0,:]

array([1, 2, 3])

## Subset of arrays

In [85]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [86]:
# subset of 2x2 array from the original array a
a_sub= a[:2,:2]
print(a_sub)

[[1 2]
 [4 5]]


In [87]:
# here value of 1 should be update to 12
a_sub[0,0]=12
print(a_sub)

[[12  2]
 [ 4  5]]


In [88]:
# Modifying the subset will automatically update the original array as well
print(a)

[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [89]:
# MODIFYING ARRAY USING transpose()
# numpy.transpose()- permutethe dimension of array
# Syntax:- numpy.transpose(array)
np.transpose(a)

array([[12,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9]])

In [90]:
# append()- adds values at the end of the array
# Syntax:- numpy.append(array,axis)

In [91]:
# Adding the new array to 'a' as a row
a_row = np.append(a,[[10,11,14]],axis=0)
print(a_row)

[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 14]]


In [94]:
# Adding the new array to 'a' as a row
col = np.array([21,22,23]).reshape(3,1)
print(col)

[[21]
 [22]
 [23]]


In [95]:
a_col = np.append(a,col,axis=1)
print(a_col)

[[12  2  3 21]
 [ 4  5  6 22]
 [ 7  8  9 23]]


In [97]:
## insert()- adds values at a given position and axis in an array
# Syntax:- numpy.insert(array,obj,values,axis)
# array:- inpur array
# obj:- index position
# values:- array of values to be inserted
# axis:- axis along which values should be insert

print(a)

[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [98]:
# insert new array along row and at the 1st index position
a_ins = np.insert(a,1,[13,15,16],axis=0)
print(a_ins)

[[12  2  3]
 [13 15 16]
 [ 4  5  6]
 [ 7  8  9]]


In [99]:
# delete() - removes values at a given position and axis in an array
# Syntax:- numpy.delete(array,obj,axis)
# array:- inpur array
# obj:- indicate array to be removed or it's position


In [100]:
# delete 3 row from the existing array _ins
a_del = np.delete(a_ins,2,axis=0)
print(a_del)

[[12  2  3]
 [13 15 16]
 [ 7  8  9]]


# Matrix

In [22]:
# Create a matrix
# matrix() - returns a matrix from an array type object or string of data
# Syntax- numpy.matrix(data)

import numpy as np
a = np.matrix("1,2,3,4;4,5,6,7;7,8,9,10")
print(a)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


### Matrix property

In [23]:
# shape() - returns no. of rows and column from matrix
a.shape

(3, 4)

In [27]:
# shape[0] - returns the no. of rows
a.shape[0]

3

In [28]:
# shape[1] - returns the no. of columns
a.shape[1]

4

In [29]:
# size() - returns the number of elements in matrix
a.size

12

### Modifying matrix

In [30]:
# using insert()
# insert() - adds valuess at a given position and axis in a matrix
# Syntax:- numpy.insert(matrix,obj,values,axis)
# matrix- input matrix
# obj- index position
# values- matrix of values to be insert
# axis- axis along which values should be insert

In [38]:
a = np.matrix("1,2,3,4;4,5,6,7;7,8,9,10")
print(a)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [39]:
# adding the matrix 'col_new' as a new column to 'a'
col_new = np.matrix("2,3,4")
print(col_new)
a = np.insert(a,0,col_new,axis=1)
print(a)

[[2 3 4]]
[[ 2  1  2  3  4]
 [ 3  4  5  6  7]
 [ 4  7  8  9 10]]


In [41]:
# adding the matrix 'row_new' as a new row to 'a'
row_new = np.matrix("4,5,6,7,9")
print(row_new)
a = np.insert(a,0,row_new,axis=0)
print(a)

[[4 5 6 7 9]]
[[ 4  5  6  7  9]
 [ 2  1  2  3  4]
 [ 3  4  5  6  7]
 [ 4  7  8  9 10]]


In [43]:
# Modifying maxtrix using index
# element of amatrix can be modified using index number
print(a)

[[ 4  5  6  7  9]
 [ 2  1  2  3  4]
 [ 3  4  5  6  7]
 [ 4  7  8  9 10]]


In [44]:
# in above matrix the value 1 should be update to -3
a[1,1]=-3
print(a)

[[ 4  5  6  7  9]
 [ 2 -3  2  3  4]
 [ 3  4  5  6  7]
 [ 4  7  8  9 10]]


In [45]:
# accessing element of a matrix using index
print(a[2,3])

6


In [48]:
# extract elements from second row of matrix 'a'
print(a[1,:])

[[ 2 -3  2  3  4]]


In [51]:
# extract elements from 3rd row of matrix 'a'
print(a[:,2])

[[6]
 [2]
 [5]
 [8]]


In [52]:
# extract element with index(1,2) from 'a'
print(a[1,2])

2


## Matrix operation

In [53]:
# matrix addition
# numpy.add()- performs elementwise addition between matrices
# Syntax:- numpy.add(matrix_1,matrix_2)

In [57]:
A = np.matrix(np.arange(0,20)).reshape(5,4)
B = np.matrix(np.arange(20,40)).reshape(5,4)
print(A)
print('\n')
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [58]:
np.add(A,B)  # I adds elementwise

matrix([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])

In [63]:
# matrix substraction
# numpy.subtract()- performs elementwise subtract between matrices
# Syntax:- numpy.subtract(matrix_1,matrix_2)
np.subtract(A,B)

matrix([[-20, -20, -20, -20],
        [-20, -20, -20, -20],
        [-20, -20, -20, -20],
        [-20, -20, -20, -20],
        [-20, -20, -20, -20]])

In [65]:
# matrix multiply
# numpy.dot()- performs matrix multiplication between two matrices
# Syntax:- numpy.dot(matrix_1,matrix_2)
np.dot(A,B)
# it gives error because for multiplication of matrices,column of first matix= row of second matrix

ValueError: shapes (5,4) and (5,4) not aligned: 4 (dim 1) != 5 (dim 0)

In [69]:
B = np.transpose(B)
print(B)

[[20 24 28 32 36]
 [21 25 29 33 37]
 [22 26 30 34 38]
 [23 27 31 35 39]]


In [70]:
np.dot(A,B)

matrix([[ 134,  158,  182,  206,  230],
        [ 478,  566,  654,  742,  830],
        [ 822,  974, 1126, 1278, 1430],
        [1166, 1382, 1598, 1814, 2030],
        [1510, 1790, 2070, 2350, 2630]])

NOTE:- we also use numpy.matmul() and @ can be also be used for matrix multipication

In [74]:
A@B

matrix([[ 134,  158,  182,  206,  230],
        [ 478,  566,  654,  742,  830],
        [ 822,  974, 1126, 1278, 1430],
        [1166, 1382, 1598, 1814, 2030],
        [1510, 1790, 2070, 2350, 2630]])

In [73]:
np.matmul(A,B) 

matrix([[ 134,  158,  182,  206,  230],
        [ 478,  566,  654,  742,  830],
        [ 822,  974, 1126, 1278, 1430],
        [1166, 1382, 1598, 1814, 2030],
        [1510, 1790, 2070, 2350, 2630]])

In [75]:
# WE WANT TO PERFORM ELEMENTWISE MULTIPLICATION
# matrix elementwise multiplication
# numpy.multiply()- performs elementwise multiply between matrices
# Syntax:- numpy.multiply(matrix_1,matrix_2)
np.multiply(A,np.transpose(B))

matrix([[  0,  21,  44,  69],
        [ 96, 125, 156, 189],
        [224, 261, 300, 341],
        [384, 429, 476, 525],
        [576, 629, 684, 741]])

In [76]:
# matrix elementwise division
# numpy.divide()- performs elementwise division between matrices
# Syntax:- numpy.divide(matrix_1,matrix_2)
np.divide(A,np.transpose(B))

matrix([[0.        , 0.04761905, 0.09090909, 0.13043478],
        [0.16666667, 0.2       , 0.23076923, 0.25925926],
        [0.28571429, 0.31034483, 0.33333333, 0.35483871],
        [0.375     , 0.39393939, 0.41176471, 0.42857143],
        [0.44444444, 0.45945946, 0.47368421, 0.48717949]])

# Linear Algebra

In [77]:
# DETERMINANT OF MATRIX

In [79]:
# numpy.linalg.det() - returns determinants of matrix
A1 = np.matrix('1,2;3,4')
print(A1)

[[1 2]
 [3 4]]


In [81]:
np.linalg.det(A1)

-2.0000000000000004

In [82]:
x = np.matrix('4,5,16,7;2,-3,2,3;3,4,5,6;4,7,8,9')
print(x)

[[ 4  5 16  7]
 [ 2 -3  2  3]
 [ 3  4  5  6]
 [ 4  7  8  9]]


In [84]:
det_matix = np.linalg.det(x)
print(det_matix)

128.00000000000009


In [85]:
# RANK OF MATRIX

In [86]:
# numpy.linalg.matrix_rank() - returns rank of matrix
# Syntax:- numpy.linalg.matrix_rank(matrix)
print(x)
rank_matrix = np.linalg.matrix_rank(x)
print(rank_matrix )

[[ 4  5 16  7]
 [ 2 -3  2  3]
 [ 3  4  5  6]
 [ 4  7  8  9]]
4


In [87]:
# inverse of matrix ( A INVERSE = 1/determinants(A)* adj(A))

In [88]:
# numpy.linalg.inv()- returns the multiplicative inverse of a matrix
# Syntax:- numpy.linalg.inv(matrix)
A = np.matrix("3,1,2;3,2,5;6,7,8")
print(A)

[[3 1 2]
 [3 2 5]
 [6 7 8]]


In [90]:
inv_matrix = np.linalg.inv(A)
print(inv_matrix)

[[ 0.57575758 -0.18181818 -0.03030303]
 [-0.18181818 -0.36363636  0.27272727]
 [-0.27272727  0.45454545 -0.09090909]]


In [91]:
B = np.matrix("2,1,2;1,0,1;3,1,3")
print(B)

[[2 1 2]
 [1 0 1]
 [3 1 3]]


In [93]:
np.linalg.det(B)

0.0

In [92]:
inverse_matrix = np.linalg.inv(B)
print(np.linalg.inv(A)) ## IT SHOW ERROR BECAUSE WE KNOW,inverse does not exist for a singular matrix

LinAlgError: Singular matrix

## System of Linear equation

In [94]:
# consider three equation
#        3x+y+2z=2
#        3x+2y+5z=-1
#        6x+7y+8z=3

# we can write in the form of  Ax=b
# x = inv(A)*b

In [95]:
# numpy.linalg.solve() - returns the solution of Ax=b
# Syntax:- numpy.linalg.solve(matrix_A,matrix_b)

In [96]:
A = np.matrix('3,1,2;3,2,5;6,7,8')
b = np.matrix('2;-1;3') # we can also weite as b = np.matrix('2,-1,3').transpose()
print(A)
print('\n')
print(b)

[[3 1 2]
 [3 2 5]
 [6 7 8]]


[[ 2]
 [-1]
 [ 3]]


In [102]:
sol_linear = np.linalg.solve(A,b)
print(sol_linear)

[[ 1.24242424]
 [ 0.81818182]
 [-1.27272727]]
