In [1]:
strsample = 'learning'
print(strsample)

learning


In [2]:
lstnumber = [1,2,3,3,3,4,5]
print(lstnumber)

[1, 2, 3, 3, 3, 4, 5]


In [3]:
lstsample = [1,2,3,'a','sam',2]
print(lstsample)

[1, 2, 3, 'a', 'sam', 2]


In [4]:
from array import *   # importing array module

arrsample = array('i',[1,2,3,4])   # array
# print array sample
for x in arrsample: print(x)

1
2
3
4


In [5]:
tupsample = (1,2,3,4,3,'py')    # tuple

In [6]:
tuplesample = 1,2,'sample'     # tuple packing
print(tuplesample)

(1, 2, 'sample')


In [7]:
dicsample = {1:'first' , 'second':2,3:3,'four':'4'}   # dictionary
print(dicsample)

{1: 'first', 'second': 2, 3: 3, 'four': '4'}


In [8]:
# Creating dictionary using 'dict' keyword
dict_list = dict([('first',1),('second',2),('four',4)])
dict_list

{'first': 1, 'second': 2, 'four': 4}

In [9]:
setsample = {'example',24,87.5,'data',24,'data'}
setsample

{24, 87.5, 'data', 'example'}

In [10]:
# we can also create set using 'set' keyword
set('example')

{'a', 'e', 'l', 'm', 'p', 'x'}

In [11]:
rangesample = range(1,12,4)   # built-in sequence type used for lopping

print(rangesample)

for x in rangesample:print(x)

range(1, 12, 4)
1
5
9


# String: Indexing

In [12]:
strsample = 'learning'

In [13]:
strsample.index('l')

0

In [15]:
strsample.index('ning')

4

In [16]:
strsample[7]

'g'

In [18]:
strsample[-2]

'n'

In [19]:
strsample[-5]

'r'

# List: Indexing

## Syntax: list_name(element,start,end)

In [20]:
lstsample = [1,2,'a','sam',2]  # list

In [24]:
lstsample.index('sam')

3

In [22]:
lstsample[2]

'a'

In [23]:
lstsample[-1]

2

# Array: Indexing

In [26]:
from array import *

In [27]:
arrsample = array('i',[1,2,3,4])   # array with integer type

In [28]:
for x in arrsample: print(x)

1
2
3
4


In [29]:
arrsample[-3]

2

# Tuple: Indexing

In [32]:
tupsample = (1,2,3,4,3,'py') 

In [33]:
tupsample.index('py')

5

In [34]:
tupsample[2]

3

# Set: Indexing

In [35]:
setsample = {'example',24,87.5,'data',24,'data'}

In [36]:
setsample[4]  # it show error because we know that set doesnot follow sequential data

TypeError: 'set' object is not subscriptable

# Dictionary: Indexing

In [37]:
dicsample = {1:'first' , 'second':2,3:3,'four':'4'}   # dictionary

In [38]:
dicsample[2] ## KeyError:2 - indexing by values is not aplicable in dictionary

KeyError: 2

In [40]:
dicsample[1]   # to find the value corresponding to key 1

'first'

In [41]:
dicsample ['second']    # to find the value corresponding to key second

2

# Range: Indexing

In [42]:
rangesample = range(1,12,4)   # built-in sequence type used for lopping



for x in rangesample:print(x)  # print the values of 'rangesample'

1
5
9


In [43]:
rangesample.index(0)         # ValueError: 0 is not in range

ValueError: 0 is not in range

In [44]:
rangesample.index(9)

2

In [45]:
rangesample[1]

5

In [46]:
rangesample[9]    # IndexError: range object index out of range

IndexError: range object index out of range

# Sequence data operations: Slicing

The slice object is used to slice a given sequence (string,bites,tuple,list,range)
or any object which supports sequence protocol

The syntax of slice: slice(stop)

slice(start,stop,step)

In [2]:
strsample = 'learning'

In [7]:
print(strsample)
strsample[slice(1,4,2)]

learning


'er'

In [8]:
strsample[:]

'learning'

In [25]:
lstsample = [1,2,'a','sam',2]

In [26]:
print(lstsample)
print(lstsample[:3])   # slicing starts at the beginning index at the list
print(lstsample[2:])

[1, 2, 'a', 'sam', 2]
[1, 2, 'a']
['a', 'sam', 2]


In [27]:
lstsample[2:4]

['a', 'sam']

In [28]:
dicsample = {1:'first' , 'second':2,3:3,'four':'4'}   # dictionary

In [29]:
dicsample[1:'second']     # TypeError: unhashable type: 'slice'

TypeError: unhashable type: 'slice'

In [16]:
setsample = {'example',24,87.5,'data',24,'data'}

In [18]:
setsample[1:2]       # TypeError: 'set' object is not subscriptable

TypeError: 'set' object is not subscriptable

In [20]:
from array import *

In [22]:
arrsample = array('i',[1,2,3,4])   # array with integer type

In [30]:
for x in arrsample: print(x)
arrsample[1:]

1
2
3
4


array('i', [2, 3, 4])

In [31]:
arrsample[1:-1]

array('i', [2, 3])

In [33]:
rangesample = range(1,12,4)   # built-in sequence type used for lopping



for x in rangesample:print(x)  # print the values of 'rangesample'

1
5
9


In [35]:
for x in rangesample: print(x)
print(rangesample[:-1])

1
5
9
range(1, 9, 4)


# Sequence data operations: Concatenation

## Syntax: ',' , '+' , '+='

In [36]:
print(strsample + ' ','python')
print(strsample)
newstring = strsample+' ','python'
print(newstring)

learning  python
learning
('learning ', 'python')


In [37]:
print(lstsample)
lstsample+['py']

[1, 2, 'a', 'sam', 2]


[1, 2, 'a', 'sam', 2, 'py']

In [38]:
print(arrsample)
arrsample+[50,60]  # TypeError: can only append array (not "list") to array


array('i', [1, 2, 3, 4])


TypeError: can only append array (not "list") to array

In [39]:
arrsample + array('i',[50,60])

array('i', [1, 2, 3, 4, 50, 60])

In [45]:
tupsample = (1,2,3,4,3,'py') 

In [46]:
tupsample+=('th','on')
print(tupsample)

(1, 2, 3, 4, 3, 'py', 'th', 'on')


In [47]:
print(setsample)
setsample=setsample,24
print(setsample)

{24, 'example', 'data', 87.5}
({24, 'example', 'data', 87.5}, 24)


# Sequence data operations: Multiplication
## syntax: object*integer

In [4]:
strsample = 'learning'

In [5]:
strsample *=3
print(strsample )

learninglearninglearning


In [16]:
lstsample = [1,2,'a','sam',2]

In [17]:
lstsample*2

[1, 2, 'a', 'sam', 2, 1, 2, 'a', 'sam', 2]

In [18]:
lstsample[1]*=2    
print(lstsample)

[1, 4, 'a', 'sam', 2]


In [19]:
lstsample[3]*2 

'samsam'

In [20]:
lstsample[2]*=2    
print(lstsample)

[1, 4, 'aa', 'sam', 2]


In [21]:
lstsample[2]*2

'aaaa'

In [22]:
tupsample = (1,2,3,4,3,'py') 

In [23]:
tupsample[2:4]*2

(3, 4, 3, 4)

In [24]:
from array import *

arrsample = array('i',[1,2,3,4])   # array with integer type

for x in arrsample: print(x)

1
2
3
4


In [25]:
arrsample*2

array('i', [1, 2, 3, 4, 1, 2, 3, 4])

In [30]:
rangesample = range(1,12,4)   # built-in sequence type used for lopping



for x in rangesample:print(x)  # print the values of 'rangesample'

1
5
9


In [31]:
rangesample*2     # TypeError: unsupported operand type(s) for *: 'range' and 'int'

TypeError: unsupported operand type(s) for *: 'range' and 'int'

# General sequence data methods

## String Methods

In [8]:
strsample = 'learning is fun !'
print(strsample)

learning is fun !


In [9]:
strsample.capitalize()

'Learning is fun !'

In [10]:
strsample.casefold()

'learning is fun !'

In [11]:
strsample.capitalize()

'Learning is fun !'

In [12]:
strsample.title()

'Learning Is Fun !'

In [13]:
strsample.swapcase()

'LEARNING IS FUN !'

In [14]:
strsample.find('n')

4

In [15]:
strsample.count('a')

1

In [16]:
strsample.replace('fun','joyful')

'learning is joyful !'

In [17]:
strsample.isalnun()   ## some mistake i am not understanding

AttributeError: 'str' object has no attribute 'isalnun'

In [18]:
name1 = 'GITTA'
name2 = 'Pvt'
name3 = 'Ltd'

In [19]:
name = '{} {}. {}.'.format(name1,name2,name3)
print(name)

GITTA Pvt. Ltd.


# The below code will show all the function that we can use for the particular varible:

In [20]:
print(dir(name))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [21]:
print(help(str))

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  

In [22]:
print(help(str.find))

Help on method_descriptor:

find(...)
    S.find(sub[, start[, end]]) -> int
    
    Return the lowest index in S where substring sub is found,
    such that sub is contained within S[start:end].  Optional
    arguments start and end are interpreted as in slice notation.
    
    Return -1 on failure.

None


# Sequence datatype object initialization

In [73]:
strsample = 'learning is fun !'

In [74]:
lstsample = [1,2,'a','sam',2]

In [75]:
from array import * 

In [76]:
arrsample = array('i',[1,2,3,4])

In [77]:
tupsample = (1,2,3,4,3,'py')

In [78]:
dictsample = {1:'first' , 'second':2,3:3,'four':'4'}   # dictionary

In [30]:
setsample = {'example',24,87.5,'data',24,'data'}

keys = (1,'second',3,'foue')

rangesample = range(1,12,4)
for x in rangesample:print(x)

1
5
9


# len(object) returns number of elements in the object

accept object type: string,list,array,tuple,dictionary,set,range

In [31]:
print("No. of elements in the object :")
print(" string = {}, list = {}, array = {}, tuple = {}, \
      dictionary = {}, set = {}, range = {} ".format(len(strsample),len(lstsample),
      len(arrsample),len(tupsample),len(dictsample),len(setsample),len(rangesample)))

No. of elements in the object :
 string = 17, list = 5, array = 4, tuple = 6,       dictionary = 4, set = 4, range = 3 


In [32]:
print(lstsample)

[1, 2, 'a', 'sam', 2]


In [33]:
lstsample.reverse()
print(lstsample)

[2, 'sam', 'a', 2, 1]


# The clear() method removes all items from the object

Supports sequence data: list,dictionary,set

In [40]:
lstsample.clear()
print(lstsample)

[]


In [41]:
dictsample.clear()
print(dictsample)

{}


In [42]:
setsample.clear()
print(setsample)

set()


# append() Adds an element at the end of the object

Supported datatypes: array,list,set

In [34]:
arrsample.append(3)
print(arrsample)

array('i', [1, 2, 3, 4, 3])


In [35]:
print(lstsample)

[2, 'sam', 'a', 2, 1]


In [36]:
lstsample.append([2,4])
print(lstsample)

[2, 'sam', 'a', 2, 1, [2, 4]]


In [37]:
setsample.append(20)   #  AttributeError: 'set' object has no attribute 'append'
print(setsample)

AttributeError: 'set' object has no attribute 'append'

In [38]:
setsample.add(20)    # add() takes single parametre(element) which need to be added in the set
 
print(setsample)

{20, 87.5, 24, 'example', 'data'}


# update() :- function in set adds element from a set (passed as an argument) to the set

- This method take only single argument

- The single argument can be a set, list, tuple or a dictionary

- It automatically converts into a set and adds to the set

In [39]:
setsample.update([5,10])
print(setsample)

{5, 10, 20, 87.5, 24, 'example', 'data'}


# Dictionary Methods

In [40]:
print(dictsample)

{1: 'first', 'second': 2, 3: 3, 'four': '4'}


In [41]:
dictsample["five"] = 5
print(dictsample)

{1: 'first', 'second': 2, 3: 3, 'four': '4', 'five': 5}


In [42]:
dictsample.update(five = 5)

print(dictsample)

{1: 'first', 'second': 2, 3: 3, 'four': '4', 'five': 5}


In [43]:
list(dictsample)

[1, 'second', 3, 'four', 'five']

In [44]:
len(dictsample)

5

In [45]:
dictsample.get("five")

5

In [46]:
dictsample.keys()

dict_keys([1, 'second', 3, 'four', 'five'])

In [47]:
dictsample.items()

dict_items([(1, 'first'), ('second', 2), (3, 3), ('four', '4'), ('five', 5)])

# insert() :- insert the element at the specified index of the object

- Supported datatype: array,lisr

In [48]:
print(arrsample)

array('i', [1, 2, 3, 4, 3])


In [49]:
arrsample.insert(1,100)   # inserting the element 100 at 2nd position
                     # first argument is position,and second argument is element tht should be added
print(arrsample)

array('i', [1, 100, 2, 3, 4, 3])


In [50]:
lstsample.insert(5,24)
print(lstsample)

[2, 'sam', 'a', 2, 1, 24, [2, 4]]


# pop() :- removes the elements at the given index from the object and prints the same

- default values is -1, which returns the last items

- Supported datatypes: array,list,set,dictionary

In [51]:
arrsample.pop()

3

In [52]:
print(arrsample)

array('i', [1, 100, 2, 3, 4])


In [54]:
print(lstsample)
lstsample.pop(4)           # deleting the 5th element from the list

[2, 'sam', 'a', 2, 1, 24, [2, 4]]


1

In [55]:
print(dictsample)
dictsample.pop('second')

{1: 'first', 'second': 2, 3: 3, 'four': '4', 'five': 5}


2

In [56]:
dictsample.pop(3)

3

### Set is an unordered sequence and hence pop is not usually used.

# remove() :- method remove the first occurence of the elements with the specified value

- Supported datatypes: array,list,dictionary,set

In [57]:
print(arrsample)

array('i', [1, 100, 2, 3, 4])


In [58]:
arrsample.remove(0)      # ValueError: array.remove(x): x not in array


ValueError: array.remove(x): x not in array

In [59]:
arrsample.remove(2)
print(arrsample)

array('i', [1, 100, 3, 4])


In [60]:
print(lstsample)
lstsample.remove('sam')
print(lstsample)

[2, 'sam', 'a', 2, 24, [2, 4]]
[2, 'a', 2, 24, [2, 4]]


In [62]:
print(setsample)
setsample.remove(57)    # KeyError: 57

{5, 10, 20, 87.5, 24, 'example', 'data'}


KeyError: 57

In [64]:
setsample.discard(57)    # The set remains unchanged if element passed discard() method doesn't exist
 
print(setsample)

{5, 10, 20, 87.5, 24, 'example', 'data'}


# del   :- deletes the entire object of any data sets 

- Syntax: del obj_name

- del is a python keyword 

- obj_name can be variable, user-defined,lists,items within lists,dictionaries etc.

In [65]:
del setsample
print(setsample)

NameError: name 'setsample' is not defined

In [66]:
del arrsample
print(arrsample)

NameError: name 'arrsample' is not defined

In [67]:
del lstsample
print(lstsample)

NameError: name 'lstsample' is not defined

In [68]:
del lstsample[2]
print(lstsample)

NameError: name 'lstsample' is not defined

In [69]:
del lstsample[1:3]
print(lstsample)

NameError: name 'lstsample' is not defined

In [70]:
del lstsample[:]
print(lstsample)

NameError: name 'lstsample' is not defined

In [71]:
del dictsample
print(dictsample)

NameError: name 'dictsample' is not defined

# extend()- methods adds the specified list elements                      ( or any iterable- list,set,tuple,etc.) to the end of the current list

# Array operations

In [79]:
arrsample.extend((4,5,3,5))
print(arrsample)

array('i', [1, 2, 3, 4, 4, 5, 3, 5])


In [80]:
print(arrsample.extend(['sam']))   # TypeError: an integer is required (got type str)

TypeError: an integer is required (got type str)

In [81]:
arrsample.fromlist([3,4])
print(arrsample)

arrsample.tolist()

array('i', [1, 2, 3, 4, 4, 5, 3, 5, 3, 4])


[1, 2, 3, 4, 4, 5, 3, 5, 3, 4]

# List operations

- Create a list using loop and function

In [ ]:
def number(n):
    return [i for i in range(1,n+1)]

In [ ]:
number(10)

# Set operations

## Set Sample

* A set is an unordered collecton of items
   - Every elements is unique (no duplicates)
   - Sets can be used to perform mathematical set operations like
   union, intersection symmetric,difference etc.
   

In [82]:
A = {'example',24,87.5,'data',24,'data'}
print(A)

{24, 'example', 'data', 87.5}


In [84]:
B = {24,87.5}
print(B)

{24, 87.5}


In [85]:
print(A | B)  # union of A and B is a set of all element from both sets
A.union(B)   # using union() on B

{87.5, 24, 'example', 'data'}


{24, 87.5, 'data', 'example'}

In [86]:
print(A & B)   # intersection of A and B is a set of all element that are common in both sets
A.intersection(B)   # using intersection() on B    

{24, 87.5}


{24, 87.5}

# NumPy

In [1]:
my_list = [1,2,3,4,5,6]
print(my_list)

[1, 2, 3, 4, 5, 6]


In [2]:
import numpy as np

In [3]:
array = np.array(my_list,dtype=int)
print(array)

[1 2 3 4 5 6]


In [4]:
print(type(array))
print(len(array))
print(array.ndim)
print(array.shape)

<class 'numpy.ndarray'>
6
1
(6,)


In [5]:
array2 =array.reshape(3,2)
print(array2)
array2.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [6]:
array3 =array.reshape(3,-1)
print(array3)

print(array3.shape)
print('\n')
print(array3.ndim)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


2


In [7]:
##  Initiallizing numpy arrays from nested Python list

my_list2 = [1,2,3,4,5]
my_list3 = [2,3,4,5,6]
my_list4 = [3,4,5,6,7]

mul_arr = np.array([my_list2,my_list3,my_list4])
print(mul_arr)
print(mul_arr.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
(3, 5)


In [8]:
mul_arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7]])

# NumPy-Attributes

In [9]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
b= a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
r = range(24)

In [13]:
print(r)

range(0, 24)


In [16]:
# an array of evenly spaced numbers
a = np.arange(24)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [19]:
# reshaping the array 'a'

b = a.reshape(6,4,1)
print(b)


[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


# NumPy Arthemetic operations

In [20]:
x = np.array([[1,2],[3,4]], dtype = np.float64)
y = np.array([[5,6],[7,8]], dtype = np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [21]:
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [22]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [23]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [24]:
print(x.dot(y))   # multipication of two matrices
print(np.dot(x,y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [26]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [31]:
print(x)

[[1. 2.]
 [3. 4.]]


In [27]:
print(np.sum(x))         # #  compute overall sum 

10.0


In [28]:
print(np.sum(x,axis = 0))    #  compute sum of each column

[4. 6.]


In [30]:
 print(np.sum(x,axis = 1))    #  compute sum of each row

[3. 7.]


# Assignment 2


In [33]:
# Question1
job = "chemist"

In [37]:
job[len(job)-1]


't'

In [39]:
job[-1]

't'

In [45]:
# Question 2
nst_tup = ("System",(60,75,45),(15,3,12))
get_num = nst_tup[1][1]
print(get_num)

75


In [47]:
# Question 3
new_list = [13,23,18,64,51]
new_list[4] = True
print(new_list)

[13, 23, 18, 64, True]


In [49]:
# Question 4
scores = (12,25,32,39,44)
f_score, *bw_s, l_score = scores
print("Output is :",f_score,"and",bw_s,"and",l_score)

Output is : 12 and [25, 32, 39] and 44


In [50]:
# QUESTION 5
word = "occurrence"
for ltr in range(len(word)):
    if ltr % 3 == 0:
        print(word[ltr])

o
u
e
e


In [54]:
# qUESTION 6
t = (2,2)
print(t,type(t))
y = ['h','4','3']
print(y,type(y))
r = ('v',)
print(r,type(r))
s = ('w')
print(s,type(s))

(2, 2) <class 'tuple'>
['h', '4', '3'] <class 'list'>
('v',) <class 'tuple'>
w <class 'str'>


In [55]:
# Question 8 
city = {'Delhi':3,'Bengaluru':5,'Chennai':4,'Kolkata':6,'Mumbai':7}

In [56]:
city['Bengaluru']

5

In [59]:
list(city.values())[1]

5